### ISSUE TITLE
Standardize PVC component names

### ISSUE THREAD

**Issue by manuelpuyol** [primer/view_components#676]
## Overview

We don't have a standard for our component names, having three different variants:

- `Primer::ButtonComponent` - with suffix
- `Primer::AutoComplete` - no suffix
- `Primer::Alpha::ButtonMarketing` - status as a module

This causes confusion and a not ideal developer experience, so we should have a single naming standard.

## Proposal

Rename all components to have their status as a module and remove the `Component` suffix.

Examples:

- `Primer::ButtonComponent` -> `Primer::Beta::Button`
- `Primer::AutoComplete` -> `Primer::Beta::AutoComplete`

Removing the suffix will make working with components less verbose. Using the status as a module will help with status promotion because we can keep the previous version for some time, giving users time to migrate.

## How to migrate a component

The majority of the work is done through the `component_status_migrator` thor command. This command will move files, update references, create a deprecated component in place of the original, fix navigation in storybook and the doc site, and more.

### Run a migration

As an example, the above referenced `Primer::ButtonComponent` can be migrated with the following command line:

```shell
bundle exec thor component_status_migrator ButtonComponent --status beta
```

Note that this command specifically calls out the target status for the component in `--status beta`. If this option is left off, it will default to `alpha` and move the component into the corresponding `alpha` folder and `Alpha::` namespace. 

Be sure to set the correct status when migrating a component. Valid status entries include:

* alpha
* beta
* stable
* deprecated (not fully supported yet)

### Testing a migration

Prior to creating a pull request and marking it as ready for review, be sure to run all tests, check storybook, and check the docs site to ensure all updates have been made:

* run `script/test`
* run `script/dev`
  * go to `http://localhost:5000` to check storybook
  * go to `localhost:5400` to check the doc site

### Common errors

You may run into errors with storybook or the docs site, due to previously built site information. For example, storybook may still have the original `Primer::ButtonComponent` entry while also having the updated `Primer::Beta::Button` entry. If this happens, you will need to clean out the build cache and rebuild. One way to do that is to run the following:

1. `git clean -dfx`
2. `script/setup`

The first call to clean will remove all untracked files and folders that are not part of `.gitignore`. The second call will remove all untracked files and folders that are part of `.gitignore`. This will remove everything, including nod_modules and bundle vendor folders. After that, you'll need to run `script/setup` to reinstall and rebuild before running `script/dev` again.
 
 ### Example pull requests
 
See the component migration work that is already completed, below, for example pull requests.

### component status migrator code changes:
- [x] update `component_status_migrator.thor` script to handle `--status stable` https://github.com/primer/view_components/pull/1262
- [x] automate additional manual tasks for replacing references and updating files https://github.com/primer/view_components/pull/1269
- [x] correct the docs site nav.yml when migrating a component https://github.com/primer/view_components/pull/1276
- [x] update `component_status_migrator.thor` to support migrating from `alpha` or `beta` folder, to correct status destination https://github.com/primer/view_components/issues/1263

### todo / in progress component migrations:
- [x] Primer::LayoutComponent (needs deprecation config w/ migration guide)
- [x] Primer::Truncate (needs deprecation config w/ migration guide)
- [x] Primer::Navigation::TabComponent https://github.com/primer/view_components/pull/1730
- [x] Primer::TimelineItemComponent::BadgeComponent https://github.com/primer/view_components/pull/1729

### completed component migrations:
- [x] Primer::AutoComplete https://github.com/primer/view_components/pull/678
- [x] Primer::AutoComplete::Input https://github.com/primer/view_components/pull/678
- [x] Primer::AutoComplete::Item https://github.com/primer/view_components/pull/678
- [x] Primer::AvatarComponent https://github.com/primer/view_components/pull/687
- [x] Primer::AvatarStackComponent https://github.com/primer/view_components/pull/707
- [x] Primer::BaseButton https://github.com/primer/view_components/pull/1243
- [x] Primer::BlankslateComponent (deprecated version is still live, due to API changes)
- [x] Primer::BorderBoxComponent https://github.com/primer/view_components/pull/1255
- [x] Primer::BoxComponent https://github.com/primer/view_components/pull/1266
- [x] Primer::BreadcrumbComponent
- [x] Primer::BreadcrumbComponent::ItemComponent
- [x] Primer::ButtonComponent https://github.com/primer/view_components/pull/1271
- [x] Primer::ButtonGroup https://github.com/primer/view_components/pull/1275
- [x] Primer::ClipboardCopy https://github.com/primer/view_components/pull/1674
- [x] Primer::CloseButton https://github.com/primer/view_components/pull/1277
- [x] Primer::CounterComponent https://github.com/primer/view_components/pull/1279
- [x] Primer::DetailsComponent https://github.com/primer/view_components/pull/1280
- [x] Primer::Dropdown
- [x] Primer::Dropdown::Menu
- [x] Primer::Dropdown::Menu::Item
- [x] Primer::DropdownMenuComponent
- [x] Primer::FlashComponent
- [x] Primer::HeadingComponent https://github.com/primer/view_components/pull/1297
- [x] Primer::HiddenTextExpander https://github.com/primer/view_components/pull/1303
- [x] Primer::IconButton https://github.com/primer/view_components/pull/1397
- [x] Primer::Image https://github.com/primer/view_components/pull/1527
- [x] Primer::ImageCrop https://github.com/primer/view_components/pull/1528
- [x] Primer::LabelComponent https://github.com/primer/view_components/pull/1530
- [x] Primer::LinkComponent https://github.com/primer/view_components/pull/1532
- [x] Primer::LocalTime https://github.com/primer/view_components/pull/1687
- [x] Primer::Markdown https://github.com/primer/view_components/pull/1681
- [x] Primer::MenuComponent https://github.com/primer/view_components/pull/1682
- [x] Primer::OcticonComponent https://github.com/primer/view_components/pull/1690
- [x] Primer::OcticonSymbolsComponent https://github.com/primer/view_components/pull/1696
- [x] Primer::PopoverComponent
- [x] Primer::ProgressBarComponent
- [x] Primer::SpinnerComponent https://github.com/primer/view_components/pull/1698
- [x] Primer::StateComponent https://github.com/primer/view_components/pull/1716
- [x] Primer::SubheadComponent https://github.com/primer/view_components/pull/1720
- [x] Primer::TabContainerComponent https://github.com/primer/view_components/pull/1725
- [x] Primer::TabNavComponent
- [x] Primer::TimeAgoComponent https://github.com/primer/view_components/pull/1692
- [x] Primer::TimelineItemComponent https://github.com/primer/view_components/pull/1727
- [x] Primer::Tooltip
- [x] Primer::UnderlineNavComponent
- [x] Primer::HellipButton https://github.com/primer/view_components/pull/1726

**Comment by srt32** [comment]
I made an embarrassingly nasty script in https://github.com/primer/view_components/pull/701 that we hack on that I think should save us a bunch of time in this work.

**Comment by pouretrebelle** [comment]
This issue has been getting stale for a while, and having a mix of naming conventions in the codebase is confusing for us library engineers and the developers using it.

I think it would be good to make a concerted effort to migrate the component names (possibly in one dedicated release?) and be done with it. Manuel and I have been working on changes to the migration script so that we can alias the old name to the new name, thereby running the migration in a non-breaking way. See https://github.com/primer/view_components/pull/975

I hope we have the script complete and tested this week so we can start the migration next week if we're all happy.

**Comment by ollie-iterators** [comment]
Since https://github.com/primer/view_components/pull/1441 was merged, Primer::FlexComponent and Primer::FlexItemComponent should be removed.

**Comment by ollie-iterators** [comment]
The components Primer::LocalTime and Primer::TimeAgoComponent may be able to be removed from this issue once #1650 is merged.

**Comment by ollie-iterators** [comment]
Since https://github.com/primer/view_components/pull/1650 was merged, Primer::LocalTime and Primer::TimeAgoComponent can be removed from this issue.

**Comment by ollie-iterators** [comment]
Why is Primer::LinkComponent migrated to Primer::Beta::LinkComponent? I thought that the Component suffix should be removed from all of the components.

**Comment by mxriverlynn** [comment]
@ollie-iterators 

> Why is Primer::LinkComponent migrated to Primer::Beta::LinkComponent? I thought that the Component suffix should be removed from all of the components. 

oops! that was a mistake in the title of the PR. the component is `Primer::Beta::Link`. i've updated the PR title. don't know how long it will take for the link here to reflect that

**Comment by ollie-iterators** [comment]
The Pull Request: https://github.com/primer/view_components/pull/1729 was merged, so Primer::TimelineItemComponent::BadgeComponent can be marked as completed.

**Comment by ollie-iterators** [comment]
Since https://github.com/primer/view_components/pull/1730 was merged, Primer::Navigation::TabComponent's check box should be checked.

**Comment by ollie-iterators** [comment]
Since https://github.com/primer/view_components/pull/1877 was merged, Primer::Truncate can be checked off.

**Comment by lesliecdubs** [comment]
Thanks @ollie-iterators. @hrs can you confirm https://github.com/primer/view_components/issues/676#issuecomment-1466713881 has been completed and update the summary task list if so?

**Comment by ollie-iterators** [comment]
I don't know if Primer::LayoutComponent has been migrated yet

**Comment by hrs** [comment]
Yup, that's all right! `Primer::Truncate` has been migrated and checked off. `Primer::LayoutComponent` hasn't yet been deprecated but will be shortly!

**Comment by hrs** [comment]
Nope, but I'm working on that one right this minute. Ought to be done before *too* much longer. 😄

**Comment by ollie-iterators** [comment]
Since https://github.com/primer/view_components/issues/1263 was closed, this Issue can be closed as completed.
