### ISSUE TITLE
Update tab navigation API and make accessibility fixes

### ISSUE THREAD

**Issue by khiga8** [primer/view_components#680]
### Problem
Our Tab navigation components are missing some necessary accessibility attributes. In addition, the tab navigation component APIs are becoming really complex. For example, `UnderlineNav` can be rendered as page navigation links or panel navigation depending on a single `with_panel` attribute. Based on whether panels are rendered, the markup is totally different yet the documentation is missing the nuances for these differences. We should break down `UnderlineNav`and `TabNav` into two components, one that is specific to page navigation links, and one that is specific to panel navigation links.

### User Story
As a developer, I want an accessible tab component in my project, and I want to be aware of all the accessibility considerations.

### Exit Criteria
- [x] Ensure tab panels are labelled and have tabindex set to 0. #683 
- [x] Ensure tab panels and tab are associated with aria-controls #702 
- [x] Break UnderlineNav into UnderlineNav and UnderlinePanel #689 
- [ ] Break TabNav into TabNav and TabPanel #785

**Comment by khiga8** [comment]
**1. Markup for Navigating links**

- **Case 1:** As MAIN navigation. `nav` has implicit role of `navigation` which will make it accessible via landmarks shortcuts. This should be used sparingly.

```.html
<nav aria-label="something">
  <ul>
    <li><a>Link 1</a></li>
    <li><a>Link 2</a></li>
    <li><a>Link 3</a></li>
  <ul>
</nav>
```

- **Case 2:** As regular list of links. `div` tag when group of links are NOT main links.

```.html
<div>
  <ul>
    <li><a>Link 1</a></li>
    <li><a>Link 2</a></li>
    <li><a>Link 3</a></li>
  <ul>
</div>
```

**2. Markup for Panel navigation**

- **Case 1:** Only case. Contained within a web component which comes with associated js behavior.

```.html
<tab-container>
  <div>
    <ul role="tablist">
      <li role="presentation"><button id="tab-1" role="tab">Tab 1</li>
      <li role="presentation"><button id="tab-2" role="tab">Tab 2</li>
      <li role="presentation"><button id="tab-3" role="tab">Tab 3</li>
    <ul>
  </div>
</tab-container>
<div role="tabpanel" aria-labelledby="tab-1" tabindex="0">Panel content</div>
<div role="tabpanel" aria-labelledby="tab-2" tabindex="0">Panel content</div>
<div role="tabpanel" aria-labelledby="tab-3" tabindex="0">Panel content</div>
```

**Comment by khiga8** [comment]
API-wise, 

- When `with_panel` is true (rendering panels), `TabNav`, `UnderlineNav` should always be `:div`. We do this right now. 
- When `with_panel` is false, `TabNav` can render either a `:div` or a `:nav`. Currently we always set `:nav`, but this should be allowed to be updated to a `:div`. 

This is made complicated by the fact that we're supporting a case in dotcom where `with_panel` is not set but consumer is rendering panels and using custom JS for panel navigation behavior. It seems we should NOT be supporting this.

**Comment by khiga8** [comment]
I'm starting to lean towards changing gears completely to have `PanelNavigation` component and `PageNavigation` component and have variants to change the styling (e.g. `:underline`, `:default`). 

The component markup can change so drastically depending on what API argument is passed in. Right now, we're needing to say things conditionally everywhere in the documentation depending on `with_panel` is true or false. If we make components based on the markup output, this will simplify the API and have documentation that is more tailored. With `@manuelpuyol`'s blessing, I will do some explorations of what this might look like.

**Comment by khiga8** [comment]
`UnderlineNav` and `TabNav` have different sets of classes and parts so a variant alone may not be enough...

Perhaps we should have `UnderlineNav`, `UnderlinePanel`, `TabNav`, `TabPanel`. Though there's some duplication, I think it might be useful in this case..

**Comment by benjiallen** [comment]
Howdy @khiga8 - just trying to work out the status of this issue and whether we're able to break up this work into multiple tickets.

Is it best to make the API changes across all components at once or can we break up the work so that we make changes to 1 component at a time?

Also, I see you have a few PRs already merged. Are you working on any other PRs related to this issue?

**Comment by khiga8** [comment]
Hi @benjiallen, I updated the issue description to reflect the work left. 
There is one open PR and one PR left to close this issue.

**Comment by benjiallen** [comment]
@khiga8 - do we need an issue created for the last task? Is there one already?

**Comment by JoseInTheArena** [comment]
> @khiga8 - do we need an issue created for the last task? Is there one already?

Linked [PR](https://github.com/primer/view_components/pull/785) to issue body.

**Comment by jscholes** [comment]
@khiga8 I have some concerns about the outlined mark-up:

> ```
> <nav aria-label="something">
>   <ul>
> ```

1. Should developers be responsible for including `aria-label` and setting it to an appropriate value?  Labelling a nav is nuanced, because it's very common for the word "navigation" to be included meaning that screen reader users end up hearing it twice.  E.g. "Main navigation navigation", where the name of the nav is "Main navigation" but the accessible role is also "navigation".
2. There is no heading between the start of the nav and list.  This would be a great opportunity to enforce headings for nav sections, but the heading must be at the correct level for the individual usage.  Happy to discuss this (and all points raised here) further.
3. The list itself has no accessible name.  Again, it would be a great place to enforce our standard pattern for multiple navs on a page, i.e. labelled outer nav, wrapping a heading and list, with the list labelled by the heading.

> ```
> <div>
>   <ul>
> ```

This is semantically meaningless, because it has no heading, label, or anything else to indicate its purpose or allow navigation to it (other than the presence of the list).  What is the intended use case for the "regular list of links"?  Could a heading and list label also be enforced here?

> ```
> <tab-container>
>   <div>
>     <ul role="tablist">
>       <li role="presentation"><button id="tab-1" role="tab">Tab 1</li>
> ```

1. You mention that this is "Contained within a web component which comes with associated js behavior", but do devs still need to set all of the ARIA attributes?  If yes, it all but guarantees that it will be implemented wrong.  How many people will understand the reasoning behind `role="presentation"` on the `<li>`s, for example?
2. There is no accessible name on the `tablist`.  This should be enforced.
3. The `tablist` isn't preceded by a heading.

Outside of the mark-up:

1. I'm not sure about enforcing the `tabindex` of `"0"` on all `tabpanel`s.  My feeling is that this should be programmatically determined based on the presence of at least one focusable element on the panel, and only set if there are none.
2. The navs and divs wrapping a list of links aren't tabs at all, so should they be discussed in a separate issue?  There are instances of tabs being incorrectly used for link-based page navigation on GitHub (e.g. https://github.com/github/github/issues/190935), so I don't want any confusion there.

**Comment by khiga8** [comment]
@jscholes Hey! Thank you for outlining your concerns. I want to note that some of the previous comments have gotten stale. One of the issues I wanted to address first was the fact that we had one component handling both page navigation and tabbed navigation behaviors. This lead to having confusing docs and component API that tried to account for two different behaviors. Let me update you with where we're at right now as well as updated markups.  I'm happy to file issues for further updates based on your feedback:

We previously had an `UnderlineNav` component which handled rendering page links and tab panel behavior. We split this up into `UnderlineNav` which is specifically for rendering page links and `UnderlinePanels` which is specifically for rendering tab panels.  (Note: There are pending discussions around the fact that we have a component that visually looks the same and acts differently. We will likely move towards having different visuals for tab panels and page navigation)

Here are examples of what we currently have.
We have the component `UnderlineNav` for page navigation links:
  - [Example of `UnderlineNav` rendered as a list within a nav](https://primer.style/view-components/components/alpha/underlinenav#default-with-nav).  In this scenario, we apply a label on the `nav` element.
  - [Example of `UnderlineNav` rendered as a list within a div](https://primer.style/view-components/components/alpha/underlinenav#with-div). In this scenario, we apply a label on the `ul` element.

We have the component `UnderlinePanels` for tab panel navigation.
  - [Example of `UnderlinePanels` rendered as a tabpanel](https://primer.style/view-components/components/alpha/underlinepanels#default). In this scenario, we apply a label to the `ul` element.

Regarding your questions:
> 1. Should developers be responsible for including aria-label and setting it to an appropriate value?

We do require the developers to pass in a label because the components have no knowledge of where it is being used and thus we cannot infer the proper label. We currently apply this label on `nav` if `nav` is rendered. For tab panels and non-landmark page links, we apply this label on the `ul` element. However, we can also note special considerations with the naming in the docs.

> 2. There is no heading between the start of the nav and list. This would be a great opportunity to enforce headings for nav sections, but the heading must be at the correct level for the individual usage. Happy to discuss this (and all points raised here) further.

This is something we should definitely consider in the next iteration of changes. It would require a visual change which should we discussed with design infra.

> 3. The list itself has no accessible name. Again, it would be a great place to enforce our standard pattern for multiple navs on a page, i.e. labelled outer nav, wrapping a heading and list, with the list labelled by the heading.

The markup given above is stale. As of now, we apply a label on the `nav` element if `nav` is rendered,  or the `ul` element. 

> 4. do devs still need to set all of the ARIA attributes? If yes, it all but guarantees that it will be implemented wrong. How many people will understand the reasoning behind role="presentation" on the <li>s, for example?

Devs will not need to set any ARIA attributes. However, they will need to pass in a label for both `UnderlineNav` and `UnderlinePanels`. The `UnderlinePanels` component also requires an `id` to be set on the tabs. However, the component will handle forwarding these props and setting the relevant ARIA attributes.

> 5. There is no accessible name on the tablist. This should be enforced.

The markup is stale. The new changes enforce this. [Example of `UnderlinePanels` rendered as a tabpanel](https://primer.style/view-components/components/alpha/underlinepanels#default)

> 6. The tablist isn't preceded by a heading.

This is another change we should consider in the next iteration of changes after discussion with designers!

> 7. I'm not sure about enforcing the tabindex of "0" on all tabpanels. My feeling is that this should be programmatically determined based on the presence of at least one focusable element on the panel, and only set if there are none.

Thanks for bringing this concern up! I'll file an issue to see if this is always determine from the component side.

> 8. The navs and divs wrapping a list of links aren't tabs at all, so should they be discussed in a separate issue? There are instances of tabs being incorrectly used for link-based page navigation on GitHub

This is definitely part of what this issue aimed to address by splitting the component into two. One component had been handling totally different behaviors which has lead to incorrect markup. 

Sorry, this got a bit long! Let me know if you have any feedback based on what we currently have and we can go from there.

**Comment by jscholes** [comment]
@khiga8 Thanks so much for the detailed response, this is incredibly helpful context.  Some thoughts:

> We do require the developers to pass in a label because the components have no knowledge of where it is being used and thus we cannot infer the proper label ... However, we can also note special considerations with the naming in the docs.

Absolutely, I wasn't meaning to infer that the components should somehow determine the most appropriate name.  More that naming things is difficult, more so when you're providing a name that you can't see and don't know what the appropriate level of verbosity is.  This leads me directly onto...

> This is something we should definitely consider in the next iteration of changes. It would require a visual change which should we discussed with design infra.

This is in relation to headings, for anyone reading out of context e.g. in an email.  I think that naming things can certainly be easier when a component has a visible heading, and in that scenario, `aria-labelledby` (or other types of text reuse) should definitely be considered.  Asking people to provide both heading text and an accessible name is often a recipe for disaster.

However, I do want to stress that off-screen/screen-reader-only headings should be a factor here too.  There will never be design buy-in on a visible heading preceding every single link list, tab list, tab panel, etc.  It will never happen and, honestly, nor should it.  Visual layout often does a good/sufficient job of conveying the purpose and/or relationship between components.

But for screen reader users, that invisible heading before the repository nav links?  Almost an immeasurable improvement to usability and navigability, assuming that it's done right (correct level etc.).  There are so many parts of GitHub which need a heading but don't have one, and it adds unnecessary seconds (or even minutes) to user flows, every single time.

And finally that brings me to...

> We currently apply this label on `nav` if `nav` is rendered. For tab panels and non-landmark page links, we apply this label on the `ul` ...

This is a great start.  I would lobby for the accessible name to always be applied to the `ul`, even when a surrounding `nav` is present.  This is because not all screen reader users find landmarks reliable enough to navigate by (given their frequent misuse), and may even have them turned off.  At which point, particularly with no heading preceding them, the `nav`'s label isn't a factor and the list has no indication of purpose.

**Comment by khiga8** [comment]
@jscholes Thank you for the additional info! 

I think we could enforce your recommendation by updating the component API to require a `heading` instead of a generic `label` argument. Additionally, we could introduce an argument that allows the heading to be hidden visually. Then the component can link the heading as the accessible name to the `nav` element as well as the rendered list. 

Just to verify though, is your recommendation to render a heading (visible or invisible) and use the heading as an accessible name something that should be considered especially for the `nav` landmark scenario, or something we should strongly consider for all these scenarios (including non-nav list of page links and tablist)?

**Comment by jscholes** [comment]
@khiga8 

> Just to verify though, is your recommendation to render a heading (visible or invisible) and use the heading as an accessible name something that should be considered especially for the `nav` landmark scenario, or something we should strongly consider for all these scenarios (including non-nav list of page links and `tablist`)?

This isn't a 100% straight forward question to answer.  I'll tackle the easier bits first:

1. For nav, there should be a heading in 100% of cases.
2. For a `div` wrapping a list of links, the number is also close to 100%, if properly used as a website component.  If someone, say, drops a list of links into a marketing article, the case is not as cut-and-dry because the heading can disrupt the hierarchy for everything that comes after it.  But I don't know if someone would be using these components in that scenario anyway?

For tab lists, I tend to think that the area of the page using the component needs a heading, rather than the tab list itself.  For example, consider the "Write"/"Preview" tabs on all GitHub commenting forms.  Those tabs don't necessarily need a heading before them, but the area of the page facilitating commenting definitely does.  As do the individual tab panels.

One last thing on accessible naming: remember the double "navigation" thing I outlined above:

> Labelling a `nav` is nuanced, because it's very common for the word "navigation" to be included meaning that screen reader users end up hearing it twice. E.g. "Main navigation navigation", where the name of the `nav` is "Main navigation" but the accessible role is also "navigation".

In this example scenario, you would need:

1. an `aria-label` of "Main" on the `nav`;
2. a heading of "Main navigation" inside the `nav`; and
3. the `ul` `aria-labelledby` the "Main navigation" heading.

This may seem over-complicated.  But programmatically, it should be fairly easy to implement in a component: if the provided heading text ends with the word "navigation", strip it off and use the new string as the value of an `aria-label` attribute on the `nav`.  Otherwise, use `aria-labelledby` on the `nav`, pointing to the heading.  In all cases, leave the heading unmodified, and label the `ul` by the heading.  Of course, I'm completely ignoring l10n here...

We should have a discussion at some point about parameterised heading levels.  I've mentioned it already on this thread, but it is always worth reiterating: all of this discussion is completely moot if the heading levels aren't set correctly.

**Comment by khiga8** [comment]
Thank you @jscholes! Filed a separate issue to follow up with your feedback: https://github.com/primer/view_components/issues/798
