### ISSUE TITLE
[Tracking] Color Modes v2 Support

### ISSUE THREAD

**Issue by jonrohan** [primer/view_components#717]
This is a tracking issue to track the support of Color Modes V2 coming to primer. https://github.com/github/design-infrastructure/issues/1388

# Todo

- [x] Drop support for presentational deprecated arguments. We currently have [presentational overrides](https://github.com/primer/view_components/blob/223aebfc97276a9489185366f96fa7dbee8dc5ec/lib/primer/classify/functional_background_colors.rb#L28-L40) that need to be cleaned up. These were added in color modes v1 work.
    - [x] Write a rubocop linter to look for old arguments
    - [x] Remove all of these old arguments from dotcom.
        * https://github.com/github/github/pull/187574
        * https://github.com/github/github/pull/187532
- [x] Migrate color classes to use `Classify::Utilities`
- [x] Workarounds for static color options
- [ ] Fix cases in dotcom of static workarounds
